import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./(components)/Header";
import Footer from "./(components)/Footer";
import ReactQueryProvider from "./(components)/ReactQueryProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Study Group",
  description: "Generated by create next app",
  icons: {
    icon: "/communtiy.jpg",
  },
};

export default function RootLayout({ children }) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ReactQueryProvider>
  );
}
